version: '3.8'

services:
  workadventure_local:
    image: nginx:alpine
    container_name: workadventure_local
    volumes:
      - ./local/src/:/var/www/workadventure:rw
      - ./local/docker/nginx/conf.d:/etc/nginx/conf.d:rw
    labels:
      - "traefik.http.routers.map.rule=Host(`map.workadventure.localhost`)"
      - "traefik.http.routers.map.entryPoints=web,traefik"
      - "traefik.http.services.map.loadbalancer.server.port=80"
      - "traefik.http.routers.map-ssl.rule=Host(`map.workadventure.localhost`)"
      - "traefik.http.routers.map-ssl.entryPoints=websecure"
      - "traefik.http.routers.map-ssl.tls=true"
      - "traefik.http.routers.map-ssl.service=map"
